name: Build TTS System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug - Check repository structure
      run: |
        echo "=== Repository Root ==="
        ls -la
        echo ""
        echo "=== Models Directory ==="
        ls -la models/ 2>/dev/null || echo "No models directory found"
        echo ""
        echo "=== Chatterbox Directory ==="
        ls -la models/chatterbox/ 2>/dev/null || echo "No chatterbox directory found"
        echo ""
        echo "=== All Dockerfiles ==="
        find . -name "Dockerfile" -type f || echo "No Dockerfiles found"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Chatterbox (if exists)
      run: |
        if [ -d "models/chatterbox" ] && [ -f "models/chatterbox/Dockerfile" ]; then
          echo "✅ Building chatterbox..."
          docker build ./models/chatterbox \
            --file ./models/chatterbox/Dockerfile \
            --tag tts-chatterbox:latest
        else
          echo "❌ Chatterbox directory or Dockerfile not found"
          echo "Directory exists: $([ -d "models/chatterbox" ] && echo "YES" || echo "NO")"
          echo "Dockerfile exists: $([ -f "models/chatterbox/Dockerfile" ] && echo "YES" || echo "NO")"
          exit 1
        fi

    - name: Build Kokkoro (if exists)
      run: |
        if [ -d "models/kokkoro" ] && [ -f "models/kokkoro/Dockerfile" ]; then
          echo "✅ Building kokkoro..."
          docker build ./models/kokkoro \
            --file ./models/kokkoro/Dockerfile \
            --tag tts-kokkoro:latest
        else
          echo "⚠️ Kokkoro model not found, skipping..."
        fi

    - name: Build Gateway (if exists)
      run: |
        if [ -d "gateway" ] && [ -f "gateway/Dockerfile" ]; then
          echo "✅ Building gateway..."
          docker build ./gateway \
            --file ./gateway/Dockerfile \
            --tag tts-gateway:latest
        else
          echo "⚠️ Gateway not found, skipping..."
        fi

    - name: List built images
      run: |
        echo "Built Docker images:"
        docker images | grep "tts-" || echo "No TTS images found"

    - name: Test basic functionality
      run: |
        # Test chatterbox container
        echo "Testing chatterbox container..."
        docker run --rm -d --name test-chatterbox -p 8002:8002 tts-chatterbox:latest || echo "Chatterbox failed to start"
        
        # Wait a bit
        sleep 10
        
        # Test health endpoint
        if curl -f http://localhost:8002/health 2>/dev/null; then
          echo "✅ Chatterbox health check passed"
        else
          echo "❌ Chatterbox health check failed"
        fi
        
        # Cleanup
        docker stop test-chatterbox 2>/dev/null || true

    - name: Show container logs on failure
      if: failure()
      run: |
        echo "=== Container Logs ==="
        docker logs test-chatterbox 2>/dev/null || echo "No chatterbox logs available"
