version: '3.8'

services:
  # Coqui TTS Service
  coqui-tts:
    image: ghcr.io/coqui-ai/tts-cpu:latest
    container_name: coqui-tts-server
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
    command: |
      python3 TTS/server/server.py 
      --model_name tts_models/en/vctk/vits 
      --host 0.0.0.0 
      --port 5002
    volumes:
      - ./data/coqui:/data
      - ./models/coqui:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # AllTalk TTS Service
  alltalk-tts:
    build:
      context: ./alltalk
      dockerfile: Dockerfile
    container_name: alltalk-tts-server
    restart: unless-stopped
    ports:
      - "7851:7851"
      - "7852:7852"
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
    volumes:
      - ./data/alltalk/outputs:/app/outputs
      - ./data/alltalk/models:/app/models
      - ./data/alltalk/voices:/app/voices
      - ./config/alltalk/config.json:/app/confignew.json
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7851/api/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Tortoise TTS Service  
  tortoise-tts:
    build:
      context: ./tortoise
      dockerfile: Dockerfile
    container_name: tortoise-tts-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/tortoise/voices:/app/voices
      - ./data/tortoise/results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Nginx Load Balancer/Proxy
  nginx:
    image: nginx:alpine
    container_name: tts-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/logs:/var/log/nginx
    depends_on:
      - coqui-tts
      - alltalk-tts
      - tortoise-tts
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  tts_data:
    driver: local
  tts_models:
    driver: local

networks:
  default:
    driver: bridge
